export const UPDATE_ITEM = "UPDATE_ITEM";
export const INIT_BILLIONAIRES = "INIT_BILLIONAIRES";
export const SET_BILLIONAIRES = "SET_BILLIONAIRES";
export const UPDATE_BILLIONAIRE = "UPDATE_BILLIONAIRE";
